name: kb4yg
description: Know Before You Go (KB4YG)

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Override version and builder number in flutter build with --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Check for newer dependencies: flutter pub outdated
# Auto-upgrade dependencies:    flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
#  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13       # store theme preference
  http: ^0.13.4                     # transfer data over internet
  provider: ^6.0.2                  # pass data through widget tree
  carousel_slider: ^4.0.0           # automatic image slider
  latlong2: ^0.8.1                  # coordinate object for ParkingLot() and ParkingMap()
  beamer: ^1.2.0                    # navigation simplifier / wrapper
  maps_launcher: ^2.0.1             # launch Google maps in browser or phone app
  flutter_map: ^0.14.0              # create custom map with pin markers
  flutter_map_marker_cluster: 0.4.4 # cluster map markers when zoomed out
  cached_network_image: ^3.2.0      # store images in cache to save data
  introduction_screen: ^3.0.0       # guide user through mobile app screens

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2    # CLI tool to generate ios/android icons (in assets/launcher)
  flutter_native_splash: ^2.1.6     # CLI tool to generate splash screen images for web/ios/android

# Specify flutter_launcher_icons settings (see https://pub.dev/packages/flutter_launcher_icons)
#   flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path: "assets/launcher/mobile_icon.png"
  adaptive_icon_background: "#ffffff"

# Specify flutter_native_splash settings (see https://pub.dev/packages/flutter_native_splash)
#   flutter pub run flutter_native_splash:create
#   flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#f4f7f5"
  color_dark: "#303030"
  image: "assets/launcher/kb4yg.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true  # include material icons & font

  assets:
    - assets/leaf-logo.png
    - assets/images/ # Static images (e.g., on home screen)
    - assets/intro/ # On-boarding gifs

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
